import { Platform } from 'react-native';

export const APP_NAME = 'isAi';

// Tab bar height to avoid content overlap (absolute-positioned tab bar)
export const TAB_BAR_HEIGHT = Platform.OS === 'ios' ? 84 : 68;

export const TOKEN_PACKS = [
  { id: 'pack_40', name: 'Starter', tokens: 40, price: 2.99, currency: 'USD' },
  { id: 'pack_120', name: 'Popular', tokens: 120, price: 6.99, currency: 'USD', popular: true },
  { id: 'pack_300', name: 'Pro', tokens: 300, price: 14.99, currency: 'USD' },
];

export const ONBOARDING_SLIDES = [
  {
    id: '1',
    title: 'Detect AI Images',
    description: 'Upload any image and our AI will analyze whether it was generated by artificial intelligence.',
    icon: 'search',
  },
  {
    id: '2',
    title: 'Instant Results',
    description: 'Get detailed analysis with confidence levels in seconds. Know what\'s real and what\'s not.',
    icon: 'zap',
  },
  {
    id: '3',
    title: 'Share & Verify',
    description: 'Share your results with others. Help build a more trustworthy digital world.',
    icon: 'share',
  },
];

export const CLASSIFICATION_LABELS = {
  ai_generated: 'AI Generated',
  likely_ai: 'Likely AI',
  uncertain: 'Uncertain',
  likely_real: 'Likely Real',
  real: 'Real Image',
} as const;

export const CLASSIFICATION_COLORS = {
  ai_generated: '#EF4444',
  likely_ai: '#F59E0B',
  uncertain: '#64748B',
  likely_real: '#3B82F6',
  real: '#10B981',
} as const;

export const AD_REWARD_TOKENS = 1;
export const SCAN_COST = 1;
